version: 0.2

env:
 variables:
  REACT_APP_SERVER_URL: 'https://2cce0d7a8c4d.ngrok.app/v1'

phases:
 pre_build:
  commands:
   - echo Logging in to Docker...
   - docker login -u $username -p $password
 build:
  commands:
   - echo building dev images...
   - docker compose up -d --build
   - echo building prod images...
   - >
     docker build \
      -f be/Dockerfile \
      -t sachdeva257/find-map-be:prod \
      --build-arg GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY \
      ./be
   - >
     docker build \
      -f fe/Dockerfile \
      -t sachdeva257/find-map-fe:prod \
      --build-arg REACT_APP_SERVER_URL=$REACT_APP_SERVER_URL \
      ./fe
 post_build:
  commands:
   - echo pushing prod images to ECR...
   - docker push sachdeva257/find-map-be:prod
   - docker push sachdeva257/find-map-fe:prod
